---
version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    volumes:
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    env_file:
      .env
    depends_on:
      - rabbitmq1
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    env_file:
      .env
    depends_on:
      - rabbitmq1
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
